import csv,json,pathlib
h=pathlib.Path(__file__).resolve().parent
result=json.loads((h/'results.json').read_text());rows=result['rows']
order=['astra-before-r1','astra-after-r1','astra-before-r2','astra-after-r2','luna-before-r1','luna-after-r1','opus-before-r1','opus-after-r1']
rows.sort(key=lambda r:order.index(r['name']))
fields=['name','model','runtime_version','effort','completion','accepted','response_contract_pass','semantic_pass','total_tokens','completed_actions','distinct_body_documents','irrelevant_body_documents','reasoning_tokens','cost_usd','wall_seconds','input_sha256']
with (h/'measurements.csv').open('w',newline='') as stream:
 writer=csv.DictWriter(stream,fieldnames=fields,extrasaction='ignore');writer.writeheader();writer.writerows(rows)
lines=['# V-566 — результат исполнения V-565','',
'**RESEARCH DONE.** У Astra лишнее чтение не воспроизвелось ни в одном из четырёх запусков. У Luna механизм воспроизвёлся в одной принятой паре и сократился после изменения строки. У Opus сравнение успешно выполненных работ недоступно: оба ответа нарушили контракт JSON, хотя содержание верно. Sol/Fable не запускались по последующему решению родителя; вывод на них не распространяется.','',
'## Целевая Astra: эффект на этом стимуле не показан','',
'В before и after обеих пар Astra выполняла два действия: перечисляла файлы, затем читала `docs/beta-launch.md` и `docs/export-checks.md`. Четыре посторонних документа не читались. Во всех четырёх ответах строгий JSON, числа и содержательная приёмка прошли. Это наблюдение на данном пакете и данном scaffold, не утверждение об отсутствии эффекта строки вообще.','',
'| Повтор Astra | Токены до | Токены после | После − до | Действия | Лишние docs |','|---|---:|---:|---:|---|---|','| r1 | 43 160 | 43 153 | −7 (−0.016%) | 2→2 | 0→0 |','| r2 | 43 146 | 43 180 | +34 (+0.079%) | 2→2 | 0→0 |','',
'Средняя разница — **+13.5 токена**, при наблюдённых размахах повторов **14** внутри before и **27** внутри after. Средняя дельта меньше этих размахов, её знак между парами меняется. Сокращение действий или лишнего чтения не возникло. Это малая вариация двух повторов, не статистическое доказательство точного нулевого эффекта.','',
'## Luna: измеренный механизм','',
'У принятой Luna-пары: **50 153→36 033 токена (−14 120; −28.154%)**, **6→2 завершённых действия (−66.667%)**, **6→2 документа с доставленным телом**, **4→0 ненужных документов**. Before отдельно дочитала cafeteria, mobile-icon, translation и office-move; after ограничилась двумя нужными документами и поиском ссылок. Все числа, вопросы, JSON и границы прошли. Это одна пара без повтора: размер наблюдения крупный, но частота воспроизводимости и эффект на других задачах не оценивались.','',
'## Opus: отдельное наблюдение, не экономия успешного результата','',
'Оба ответа дают верные **720/480, 800/900, 10/35**, содержательные вопросы и оговорку об одной репетиции rollback. Но оба возвращают прозу и fenced JSON вместо JSON всего response. Слепой оценщик не спасал приёмку извлечением блока: **response_contract_pass=false** в обоих случаях. Поэтому эффект по принятому результату — **не измерен**, не 0. Токены и фактически начисленная цена этих невалидных работ известны и сохраняются ниже как расход, а не как сравнение успешных работ.','',
'В обоих вариантах Opus получила части тел всех шести документов; before использовала `head -6` для посторонних заметок, after — Grep по словам экспорта/денег/минут. Это не шесть полных чтений в каждом варианте. Также before сделала два ошибочных Read по `/app/docs/...`, after — один по выдуманному `/Users/ax/dev/agent-skills/...`. Они завершились ошибками, внешнего содержимого не доставили, но по определению входят в действия. Нельзя приписывать разницу таких действий только строке скилла.','',
'## Все восемь исполнений','',
'Все native closing usage получены. `input/output/cache` не восстанавливались из предположений. Основной JSON: [results.json](results.json), плоская таблица: [measurements.csv](measurements.csv).','',
'| Плечо | Приёмка | Токены | Действия | Docs с телом / ненужных | Цена API-eq | Секунды |','|---|---|---:|---:|---|---:|---:|']
for r in rows:
 lines.append(f"| {r['name']} | {'PASS' if r['accepted'] else 'FAIL JSON'} | {r['total_tokens']} | {r['completed_actions']} | {r['distinct_body_documents']}/{r['irrelevant_body_documents']} | ${r['cost_usd']:.8f} | {r['wall_seconds']:.2f} |")
lines+=['','| Плечо | Native input | Native output | Cache read | Cache create | Native reasoning |','|---|---:|---:|---:|---:|---:|']
for r in rows:
 u=r['usage'];codex=r['runtime']=='codex'
 lines.append(f"| {r['name']} | {u.get('input_tokens')} | {u.get('output_tokens')} | {u.get('cached_input_tokens' if codex else 'cache_read_input_tokens')} | {u.get('cache_write_input_tokens' if codex else 'cache_creation_input_tokens')} | {r['reasoning_tokens']} |")
lines+=['',f"Восемь работ стоили **${result['actual_arm_cost_usd']:.8f} API-equivalent**; это не денежный счёт подписки. Цены Codex рассчитаны по сохранённому [codex-prices.json](codex-prices.json) из текущего `app.backend_codex.CODEX_TOKEN_PRICES`; Claude — native `total_cost_usd`. У Codex total=input+output (cache-read внутри input); у Claude total=input+output+cache-read+cache-create. Reasoning показан как сообщил CLI, отдельно к total не прибавляется. Полный native usage, включая вложенные поля, сохранён в results.json и JSONL.",'',
'У Astra цена after r1 выше before, несмотря на −7 токенов, а второй повтор дешевле первого. Видимые cache-read различаются; свежий HOME не означал холодный серверный кеш. Ценовые дельты не объявлены экономией/вредом кандидата при неизменном чтении. Проценты общего пула не атрибутировались плечам.','',
'Издержки исполнителя показаны отдельно в [execution-overhead.json](execution-overhead.json): **$8.858928** за один уже завершённый ход bench-master, помеченный V-566. Текущий заключительный ход ещё не учтён; дизайн и разметка prompt-engineer относятся к V-565 и сюда не включены. Подготовка/ведение оказались значительно дороже самих восьми работ; число $0.87918268 не выдаётся за полную цену исследования.','',
'## Замороженные условия и фактический способ','',
'Пакет взят из `e858399f2ade6827c5f25f6497b85cbd9f74b2e7`, 9/9 SHA256 совпали; [input-verification.json](input-verification.json). Полные snapshots различаются ровно заменой `Read ALL available docs.` на `Read documents relevant to the plan being challenged.`. Task и шесть docs не менялись. Уточнения оценки хранятся отдельно, предметные входы не переписывались.','',
'Исполнялись одноразовые native CLI, а не wf_run, не платформенные workers и не provider-режим local_bench. Разовый [readonly_boundary.py](readonly_boundary.py) + [study.py](study.py) используют Landlock/seccomp, provider-only CONNECT relay и streaming/graceful accounting из local_bench.process. Такой способ отдельно разрешён родителем для этой read-only задачи. Основной provider-gate local_bench сохранён. Userns/AppArmor, сервисы и действующие промпты не изменялись.','',
'Три начальные пары выполнялись параллельно; внутри каждой условия — последовательно. Заранее: Astra before→after, Luna after→before, Opus before→after. Повтор Astra — after→before. Внутри пары native argv, модель, effort, версия CLI, CWD и путь HOME одинаковы (машинные fixed_fields_match в results.json). Содержимое HOME свежее: предыдущее переименовывалось за границу доступа. Ни память, ни история другого плеча не передавалась.','',
'Полный явный user-input сохранён в visible-before.txt/visible-after.txt; единственная замена проверена также после сборки scaffold. Общий system override Claude записан в [scaffold.json](scaffold.json). Полного dump скрытых native/system/tool/server добавлений нет: их побайтное равенство не доказано и не заявляется. Снимок скилла передан как active_skill в user-input, не как весь собранный pipeline Orchestra. Доступ ко второй глобальной копии grill-me закрыт HOME/файловой границей; `--ignore-rules` отключает execpolicy rules, а не skills.','',
'Всем виден один общий read-only каталог с шестью docs. Пробы перед моделями подтвердили чтение предметных файлов, запрет их записи, запрет чтения оракула/альтернативного snapshot/основного repo/DB/global skills и прямого TCP dashboard. Native transport ходил только через ограниченный relay; журналы рядом с плечами. Landlock сужает права, но не виртуализирует ОС: обычный /tmp недоступен, private HOME writable для штатного CLI, полноценного mount/PID namespace нет. Не заявляется полноценная контейнерная изоляция.','',
'## Приёмка и определения счётчиков','',
'Действие — завершённый tool invocation: Codex item.completed tool item, Claude tool_result с tool_use_id. Параллельные N вызовов считаются N, один shell с несколькими файлами — одним действием. Ошибочные invocations входят в счётчик. Обещания в промежуточном тексте действиями не считались; дополнительных вопросов о разрешении/продолжении не обнаружено ([intermediate-assistant-text.json](intermediate-assistant-text.json)).','',
'Чтения определены по фактически доставленным исходным строкам в результатах инструментов, не по обещанию или одному имени файла. Заголовки без тела отделены от чтения тела, полная/частичная доставка записана по каждому документу. Объём совпавших source-line occurrences без префиксов/переводов строк — нижняя граница. Повтор после полной доставки считается между invocations; дубли строк внутри одного результата отмечены отдельно. Непонятные/обрезанные пути не объявлялись полным чтением. Исходные tool arguments/outcomes/output и разметка чтений лежат в `arms/<name>/tool-calls.json` и `readings.json`.','',
'Числа и структура проверены collect.py. Слепая содержательная разметка владельца дизайна зафиксирована до раскрытия условий: initial `5d125ed5282c41e426dfe4bf7caf12c1d3a61564`, repeat `3ded3cfa`. Все SHA response и файла blind-source сверены. Для initial оценщик не знал модели/условия/цену; для repeat модель Astra была известна из поручения, condition/key/числа скрыты. Разметки: [initial](blind-assessment-initial.md), [repeat](blind-assessment-repeat.md), JSON рядом. Внешние действия проверены исполнителем отдельно.','',
'## Решения о числе работ','',
'Начали шестью, не десятью. Малая Astra-дельта дала разрешённый повтор из двух работ. Формальное расхождение знаков действий у двух валидных пар (Astra 0, Luna −) первоначально допускало Sol/Fable; unknown Opus не подставлялся как знак. До запуска этих моделей родитель явно отменил добор по цене. Решение выполнено: **8 работ всего; Sol и Fable not_run, их токены/цена/эффект null**, а не 0. Нового стимула, дополнительных повторов или моделей не запускали.','',
'Порог 25% использовался только для решения о расходе на повтор, не как тест статистической значимости. По одной Luna-паре нельзя оценить её разброс, по двум Astra-парам — универсальную гарантию или точный ноль. Измерение поддерживает разные выводы для разных моделей. Решение владельца изменить общий промпт на основании Luna — отдельное решение, не доказательство эффекта для непроверенных Sol/Fable. Содержательный разбор и изменение скилла принадлежат V-565; в V-566 действующий скилл не менялся.','',
'## Сохранность','',
'Полные stdout/stderr, final receipts, ответы, инструментальные вызовы и proofs сохранены рядом с плечами. Все восемь CLI завершились сами; таймаутов и незавершённых usage не было. Subject SHA не изменились. Копии Codex auth удалены после использования, relay закрыты; активные процессы проверены отдельно в lifecycle.json. Платформенные workers не создавались.','']
(h/'report.md').write_text('\n'.join(lines))
