(() => {
'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const input=[100,100,100,120,120,140,140,120,120,120,140,120];
let q=24;
const samples=input.map((incoming,i)=>{const previous=q,analysis=incoming*.35,output=incoming*.65+30,delta=analysis-30;q+=delta/12;return {incoming,output,delta,analysis,search:incoming*.4,export:incoming*.25,ui:incoming*.6,api:incoming*.4,q,previous,wait:q*2,t:(i+1)*5};});
const state={index:11,node:'analysis',view:'network'};
const names={ui:'Интерфейс',api:'Интеграции',router:'Маршрутизатор',search:'Поиск',analysis:'Анализ',export:'Экспорт',success:'Завершено',queue:'Очередь'};
const colors={ui:'#549df1',api:'#68acdf',router:'#448ab7',search:'#168bdf',analysis:'#d99836',export:'#369caa',success:'#37a270',queue:'#d99836'};
const num=n=>Number.isInteger(Math.round(n*10)/10)?String(Math.round(n)):n.toFixed(1).replace('.',',');
const time=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const rate=(id,s)=>({router:s.incoming,success:s.output,queue:s.q}[id]??s[id]);
let space=null,storage=true,votes={};
try{votes=JSON.parse(localStorage.getItem('design-iteration-2')||'{}');if(!votes||typeof votes!=='object'||Array.isArray(votes))votes={};}catch{storage=false;}
function save(){try{localStorage.setItem('design-iteration-2',JSON.stringify(votes));$('save-status').textContent='Оценки сохранены в этой Opera.';}catch{storage=false;$('save-status').textContent='Сохранение браузером недоступно. Скачай оценки кнопкой справа.';}}
function eq(a,al,op,b,bl,c,cl){return `<div class="equation"><span class="term"><b>${num(a)}</b><small>${al}</small></span><span class="operator">${op}</span><span class="term"><b>${num(b)}</b><small>${bl}</small></span><span class="operator">=</span><span class="term result"><b>${num(c)}</b><small>${cl}</small></span></div>`;}
function bars(a,b){const max=Math.max(a,b)*1.05;return `<div class="capacity-viz"><div class="bar-line"><span>Приходит</span><span class="track"><i style="width:${a/max*100}%"></i></span><strong>${num(a)}</strong></div><div class="bar-line out"><span>Успевает</span><span class="track"><i style="width:${b/max*100}%"></i></span><strong>${num(b)}</strong></div></div>`;}
function ring(percent,color){return `<svg class="ring" viewBox="0 0 94 94" aria-label="Загрузка ${num(percent)} процентов"><circle cx="47" cy="47" r="36" stroke="#e2edf3" stroke-width="6" fill="none"/><circle class="progress" cx="47" cy="47" r="36" stroke="${color}" stroke-width="6" stroke-linecap="round" fill="none" stroke-dashoffset="${226*(1-Math.min(percent,100)/100)}"/><text x="47" y="47" text-anchor="middle">${num(percent)}%</text><text class="pct" x="47" y="61" text-anchor="middle">загрузка</text></svg>`;}
function details(id){const s=samples[state.index];let title,description,visual,extra='';
 if(id==='analysis'||id==='queue'){
  title=id==='queue'?'Откуда берутся '+num(s.wait)+' с':'Анализ не успевает';
  description=id==='queue'?'Очередь переводится в ожидание при текущей скорости.':'Лишние запросы остаются ждать. Остальные ветки справляются.';
  visual=id==='queue'?eq(s.q,'в очереди','÷',30,'за минуту',s.wait/60,'мин ожидания'):eq(s.analysis,'приходит / мин','−',30,'обработано',s.delta,'ждут / мин');
  visual+=bars(s.analysis,30);
  extra=`<div class="queue-growth"><div class="growth-title"><span>Один интервал · 5 секунд</span><span>+${num(s.delta/12)} запроса</span></div><div class="growth-vis"><strong>${num(s.previous)}</strong><span class="growth-link"></span><span class="growth-add">+${num(s.delta/12)}</span><span class="growth-link"></span><strong>${num(s.q)}</strong></div><div class="wait-strip"><span>${num(s.q)} запросов ÷ 30 в минуту × 60</span><strong>${num(s.wait)} с</strong></div><p class="tiny-proof">${num(s.delta)} за минуту → ${num(s.delta/12)} за 5 с. Очередь растёт.</p></div>`;
 }else if(id==='router'){
  title='Поток разделяется';description='Каждая ветка получает свою долю. Сумма остаётся прежней.';
  visual=`<div><div class="split-strip"><i style="width:40%;background:#53a8e6"></i><i style="width:35%;background:#e0b16b"></i><i style="width:25%;background:#5aa7ae"></i></div><div class="allocation"><span>Поиск · 40%<b>${num(s.search)}</b></span><span>Анализ · 35%<b>${num(s.analysis)}</b></span><span>Экспорт · 25%<b>${num(s.export)}</b></span></div></div>`;
  extra=`<div class="queue-growth"><div class="growth-title">Ничего не исчезает</div><div class="growth-vis"><strong>${num(s.search)} + ${num(s.analysis)} + ${num(s.export)}</strong></div><div class="wait-strip"><span>Всего распределено</span><strong>${s.incoming}/мин</strong></div></div>`;
 }else if(id==='ui'||id==='api'){
  const share=id==='ui'?.6:.4;title=names[id];description='Часть общего потока приходит через этот источник.';
  visual=eq(s.incoming,'весь поток','×',share,'доля',s[id],'запросов / мин');
  extra=`<div class="ring-layout">${ring(share*100,colors[id])}<div class="ring-words"><strong>${share*100}%</strong><span>от всего входа</span></div></div>`;
 }else if(id==='success'){
  title='Что дошло до результата';description='Поиск и экспорт проходят полностью. Анализ отдаёт 30 запросов в минуту.';
  visual=eq(s.incoming,'вход / мин','−',s.delta,'остались ждать',s.output,'завершено / мин');
  extra=`<div class="ring-layout">${ring(s.output/s.incoming*100,colors.success)}<div class="ring-words"><strong>${num(s.output/s.incoming*100)}%</strong><span>текущего входа обрабатывается</span></div></div>`;
 }else{
  const cap=id==='search'?60:36,load=s[id]/cap*100;title=names[id]+' справляется';description='Есть свободная производительность. Очередь здесь не образуется.';
  visual=`<div class="ring-layout">${ring(load,colors[id])}<div class="ring-words"><strong>${num(s[id])} / ${cap}</strong><span>вход / производительность, в минуту</span></div></div>`;
  extra=`<div class="queue-growth">${eq(cap,'может / мин','−',s[id],'приходит',cap-s[id],'запас / мин')}<p class="tiny-proof">Узкое место находится в другой ветке — анализе.</p></div>`;
 }
 return `<div class="detail-primary"><p class="eyebrow">${time(s.t)} · ${names[id]}</p><h3>${title}</h3><p class="explanation">${description}</p></div><div class="detail-calculation">${visual}</div>${extra}`;
}
function animateInspector(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 document.querySelectorAll('.inspector .track i,.float-tooltip .track i').forEach((el,i)=>el.animate([{transform:'scaleX(0)'},{transform:'scaleX(1)'}],{duration:650,delay:i*90,easing:'cubic-bezier(.2,.7,.2,1)',fill:'backwards'}));
 document.querySelectorAll('.inspector .term,.float-tooltip .term').forEach((el,i)=>el.animate([{opacity:.15,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,delay:i*140,fill:'backwards'}));
 document.querySelectorAll('.growth-add').forEach(el=>el.animate([{opacity:0,transform:'translateX(-8px)'},{opacity:1,transform:'translateX(0)'}],{duration:500,delay:350,fill:'backwards'}));
}
const nodes={ui:[28,95],api:[28,235],router:[270,165],search:[510,35],analysis:[510,165],export:[510,295],success:[790,90],queue:[790,265]};
const edges=[['ui','router'],['api','router'],['router','search'],['router','analysis'],['router','export'],['search','success'],['analysis','success'],['export','success'],['analysis','queue']];
function activeEdge(a,b){return a===state.node||b===state.node||(state.node==='queue'&&a==='router'&&b==='analysis');}
function elbow(a,b){const [ax,ay]=nodes[a],[bx,by]=nodes[b];let y1=ay+35,y2=by+35; if(a==='router')y1+=b==='search'?-14:b==='export'?14:0;if(b==='success')y2+=a==='search'?-15:a==='export'?15:0;if(b==='router')y2+=a==='ui'?-12:12;if(a==='analysis'&&b==='queue')y1+=16;const x1=ax+160,x2=bx,m=(x1+x2)/2+(a==='export'?20:a==='search'?-20:0);return `M${x1},${y1}H${m-8}Q${m},${y1} ${m},${y1+(y2>=y1?8:-8)}V${y2+(y2>=y1?-8:8)}Q${m},${y2} ${m+8},${y2}H${x2}`;}
function network(){const s=samples[state.index];let out='<title id="net-title">Сеть обработки запросов</title><desc id="net-desc">Из двух источников поток расходится в три сервиса. Анализ перегружен, и избыток остаётся в очереди.</desc><defs><pattern id="dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#d8e7f0"/></pattern><marker id="arr" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L8 4L0 8" fill="#99b9cb"/></marker></defs><rect x="12" y="15" width="970" height="360" fill="url(#dots)"/><g fill="#a1afba" font-size="9"><text x="30" y="26">ИСТОЧНИКИ</text><text x="274" y="26">РАСПРЕДЕЛЕНИЕ</text><text x="798" y="26">РЕЗУЛЬТАТ</text></g>';
 edges.forEach(([a,b])=>{const active=activeEdge(a,b);out+=`<path class="edge ${active?'active':''}" d="${elbow(a,b)}" marker-end="url(#arr)"/>`;if(active)out+=`<path class="edge-pulse" d="${elbow(a,b)}"/>`;});
 Object.entries(nodes).forEach(([id,[x,y]])=>{const active=id===state.node,color=colors[id],value=rate(id,s);out+=`<g data-node="${id}" tabindex="0" role="img" aria-label="${names[id]} ${num(value)}" transform="translate(${x},${y})"><rect class="node-plate" width="160" height="70" rx="${id==='ui'||id==='api'?20:8}" style="stroke:${active?color:'#dbe5ed'};fill:${active?'#fffaf0':'#fff'}"/><path class="hud-corner" d="M-4 12V-4H12M148 74H164V58" style="stroke:${active?color:'#b4c9d8'}"/><circle cx="15" cy="17" r="3" fill="${color}"/><text class="node-name" x="25" y="22">${names[id]}</text><text class="node-rate" x="15" y="51" style="fill:${color}">${num(value)}</text><text class="node-unit" x="75" y="51">${id==='queue'?'ждут':'запр. / мин'}</text>`;
 if(['search','analysis','export'].includes(id)){const cap={search:60,analysis:30,export:36}[id];out+=`<rect x="15" y="59" width="130" height="3" rx="1" fill="#edf2f5"/><rect x="15" y="59" width="${Math.min(value/cap,1)*130}" height="3" rx="1" fill="${color}"/>`;}
 out+='</g>';});
 out+=`<g font-size="10" fill="#92a4b3"><text x="463" y="79">40%</text><text x="463" y="205">35%</text><text x="463" y="338">25%</text><text x="712" y="281" style="fill:#ba8432">+${num(s.delta)}/мин</text></g>`;$('network-svg').innerHTML=out;
 if(!matchMedia('(prefers-reduced-motion:reduce)').matches)$('network-svg').querySelectorAll('.edge-pulse').forEach(el=>el.animate([{strokeDashoffset:44},{strokeDashoffset:0}],{duration:1400,iterations:1}));
}
function ribbon(x1,y1,x2,y2,h){const m=(x1+x2)/2;return `M${x1},${y1}C${m},${y1} ${m},${y2} ${x2},${y2}V${y2+h}C${m},${y2+h} ${m},${y1+h} ${x1},${y1+h}Z`;}
function flow(){const s=samples[state.index],k=1.6;const src=[{id:'ui',q:s.ui,y:66},{id:'api',q:s.api,y:66+s.ui*k+58}];let cursor=42;const middle=['search','analysis','export'].map(id=>{const r={id,q:s[id],y:cursor};cursor+=r.q*k+37;return r;});const outSuccess=60,outQueue=60+s.output*k+46;let code='<title id="flow-title">Баланс входа, обработки и очереди</title><desc id="flow-desc">Толщина потоков пропорциональна количеству запросов в минуту. Выход плюс прирост очереди равны входу.</desc>';let srcOffsets=[0,0],successOffset=0;
 middle.forEach(m=>{let midOffset=0;src.forEach((a,i)=>{const amount=m.q*(i===0?.6:.4),active=state.node===m.id||state.node===a.id||state.node==='router';code+=`<path data-node="${m.id}" d="${ribbon(70,a.y+srcOffsets[i],510,m.y+midOffset,amount*k)}" fill="${m.id==='analysis'?'#e4b572':'#74adcd'}" opacity="${active?.52:.2}"/>`;srcOffsets[i]+=amount*k;midOffset+=amount*k;});const done=m.id==='analysis'?30:m.q;code+=`<path data-node="${m.id}" d="${ribbon(522,m.y,1010,outSuccess+successOffset,done*k)}" fill="${m.id==='analysis'?'#dcb674':'#67ac99'}" opacity="${state.node===m.id||state.node==='success'?.5:.22}"/>`;successOffset+=done*k;if(m.id==='analysis')code+=`<path data-node="queue" d="${ribbon(522,m.y+30*k,1010,outQueue,s.delta*k)}" fill="#e7a441" opacity=".75"/>`;});
 const all=[...src.map(x=>({...x,x:58})),...middle.map(x=>({...x,x:510})),{id:'success',q:s.output,y:outSuccess,x:1010},{id:'queue',q:s.delta,y:outQueue,x:1010}];
 all.forEach(n=>{const label=n.id==='queue'?'Остаётся ждать':names[n.id],selected=n.id===state.node;code+=`<g data-node="${n.id}" tabindex="0" role="img" aria-label="${label} ${num(n.q)} в минуту"><rect x="${n.x}" y="${n.y}" width="12" height="${n.q*k}" rx="2" fill="${selected?'#bf8a34':colors[n.id]}"/><text x="${n.x}" y="${n.y-11}" style="font-size:12px;font-weight:600;fill:#4e687a" text-anchor="${n.x>900?'end':'start'}">${label} <tspan style="fill:${colors[n.id]}">${num(n.q)}/мин</tspan></text></g>`;});code+=`<text x="65" y="378" style="font-size:11px;fill:#92a0ab">Баланс: ${s.incoming} входит = ${num(s.output)} завершено + ${num(s.delta)} пополнили очередь за минуту</text>`;$('flow-svg').innerHTML=code;}
function heat(){let code='<title id="heat-title">Где сеть перегружена</title><desc id="heat-desc">Нагрузка по сервисам в каждом интервале пяти секунд. Анализ выше 100 процентов и накапливает очередь.</desc>';const x0=170,cw=73,rows=['search','analysis','export'];
 code+=`<rect x="${x0+state.index*cw-4}" y="38" width="${cw-1}" height="320" rx="7" fill="#eaf4fc"/>`;
 samples.forEach((s,i)=>{code+=`<text x="${x0+i*cw+29}" y="24" text-anchor="middle" style="font-size:10px;fill:#8599a8">${time(s.t)}</text>`;});
 rows.forEach((id,r)=>{const y=57+r*80,cap={search:60,analysis:30,export:36}[id];code+=`<text x="30" y="${y+24}" style="font-size:14px;font-weight:600;fill:#3c5b70">${names[id]}</text><text x="30" y="${y+43}" style="font-size:10px;fill:#91a2af">предел ${cap}/мин</text>`;samples.forEach((s,i)=>{const load=s[id]/cap*100,active=state.index===i&&state.node===id;code+=`<g data-node="${id}" data-index="${i}" tabindex="0" role="img" aria-label="${names[id]} ${time(s.t)} загрузка ${num(load)} процентов"><rect x="${x0+i*cw}" y="${y}" width="63" height="55" rx="7" fill="${id==='analysis'?'#e9bb77':id==='search'?'#73b7e3':'#7cbac4'}" fill-opacity="${.2+Math.min(load/170,1)*.5}" stroke="${active?'#a37736':'#fff'}" stroke-width="${active?2:1}"/><text x="${x0+i*cw+31}" y="${y+26}" text-anchor="middle" style="font-size:15px;font-weight:550;fill:${id==='analysis'?'#9b6b24':'#426e88'}">${Math.round(load)}%</text><text x="${x0+i*cw+31}" y="${y+43}" text-anchor="middle" style="font-size:9px;fill:#678496">${num(s[id])} / ${cap}</text></g>`;});});
 code+='<text x="30" y="322" style="font-size:13px;font-weight:600;fill:#a07837">Очередь</text><text x="30" y="339" style="font-size:10px;fill:#97a4ae">запросов</text>';
 samples.forEach((s,i)=>{code+=`<g data-node="queue" data-index="${i}"><rect x="${x0+i*cw+12}" y="${349-s.q*1.25}" width="37" height="${s.q*1.25}" rx="3" fill="${i===state.index?'#dfab51':'#e8d2ad'}"/><text x="${x0+i*cw+31}" y="369" text-anchor="middle" style="font-size:10px;fill:#8f9da7">${num(s.q)}</text></g>`;});$('heat-svg').innerHTML=code;}
function chart(id,queue=false){const points=samples.map((s,i)=>[46+i*62,(queue?142-(s.q-20)/25*114:142-s.incoming/160*114)]);let code='';const ys=queue?[20,30,40]:[0,40,80,120,160];ys.forEach(v=>{const y=queue?142-(v-20)/25*114:142-v/160*114;code+=`<path class="chart-gridline" d="M46 ${y}H728"/><text class="chart-axis" x="10" y="${y+3}">${v}</text>`;});
 const xy=(key)=>samples.map((s,i)=>`${46+i*62},${queue?142-(s[key]-20)/25*114:142-s[key]/160*114}`).join(' ');
 if(queue){code+=`<path d="M46 142L${xy('q').replaceAll(' ','L')}L728 142Z" fill="#f9eedb"/><polyline points="${xy('q')}" fill="none" stroke="#d4a251" stroke-width="2.5"/>`;}else{code+=`<polyline points="${xy('incoming')}" fill="none" stroke="#138afa" stroke-width="2.5"/><polyline points="${xy('output')}" fill="none" stroke="#43a77c" stroke-width="2.5"/>`;}
 [0,2,4,6,8,11].forEach(i=>code+=`<text class="chart-axis" x="${46+i*62}" y="164" text-anchor="middle">${time(samples[i].t)}</text>`);
 const x=46+state.index*62,s=samples[state.index];code+=`<path class="crosshair" d="M${x} 20V146"/>`;
 (queue?['q']:['incoming','output']).forEach(key=>{const y=queue?142-(s[key]-20)/25*114:142-s[key]/160*114;code+=`<circle cx="${x}" cy="${y}" r="4.5" fill="${key==='q'?'#daa246':key==='incoming'?'#1489f5':'#3ca976'}" stroke="white" stroke-width="2"/>`;});
 code+='<rect x="40" y="10" width="697" height="140" fill="transparent"/>';$(id).innerHTML=code;}
const signed=v=>(v>0?'+':v<0?'−':'')+num(Math.abs(v));
function metricChange(id,key,unit){const current=samples[state.index],prior=samples[state.index-1];const previous=prior?prior[key]:key==='q'?current.previous:key==='wait'?current.previous*2:null;$(id).textContent=previous===null?'Нет предыдущего отсчёта':`${num(previous)} → ${num(current[key])} · ${signed(current[key]-previous)} ${unit} за 5 с`;}
function changeChart(id,keys){let code='<path d="M46 46H728" stroke="#bccdd9"/><text x="11" y="49" class="chart-axis">0</text>';const changes=samples.slice(1).flatMap((s,i)=>keys.map(k=>s[k]-samples[i][k])),max=Math.max(1,...changes.map(Math.abs));
for(const sign of [-1,1]){const y=46-sign*32;code+=`<text x="8" y="${y+3}" class="chart-axis">${signed(sign*max)}</text><path d="M46 ${y}H728" class="chart-gridline"/>`;}
samples.forEach((s,i)=>{const x=46+i*62;if(!i){code+=`<text x="${x}" y="49" text-anchor="middle" class="chart-axis">—</text>`;return;}keys.forEach((key,j)=>{const d=s[key]-samples[i-1][key],h=Math.abs(d)/max*32,w=keys.length===1?23:13,bx=x+(j-(keys.length-1)/2)*16-w/2,color=key==='incoming'?'#1489f5':key==='output'?'#3ca976':'#d49d3e';code+=`<rect x="${bx}" y="${d>=0?46-h:46}" width="${w}" height="${Math.max(h,1)}" rx="2" fill="${color}" opacity="${i===state.index?1:.38}"/>`;});});
code+=`<path class="crosshair" d="M${46+state.index*62} 8V83"/><text x="46" y="96" class="chart-axis">первый: нет сравнения</text><text x="728" y="96" text-anchor="end" class="chart-axis">запросов/мин за 5 с</text>`;$(id).innerHTML=code;}
function updateMetrics(){const s=samples[state.index],prior=samples[state.index-1];for(const [id,k]of [['metric-in','incoming'],['metric-out','output'],['metric-delta','delta'],['metric-q','q'],['metric-wait','wait']])$(id).textContent=num(s[k]);$('metric-time').textContent=time(s.t);$('queue-change').textContent=`За последние 5 с: ${num(s.previous)} + ${num(s.delta/12)} = ${num(s.q)}`;metricChange('change-in','incoming','/мин');metricChange('change-out','output','/мин');metricChange('change-growth','delta','/мин');metricChange('change-q','q','запроса');metricChange('change-wait','wait','с');
const d=prior?s.incoming-prior.incoming:null,g=prior?s.delta-prior.delta:null;$('rate-direction').textContent=d===null?'нет сравнения':d===0?'скорость не меняется':`${d>0?'ускорение':'замедление'} ${signed(d)} /мин`;$('growth-direction').textContent=g===null?'нет сравнения':g===0?'рост с прежней скоростью':`${g>0?'растёт быстрее':'растёт медленнее'} · ${signed(g)} /мин`;
changeChart('rate-change-chart',['incoming','output']);changeChart('growth-change-chart',['delta']);}
function refresh(animate=true){updateMetrics();if(state.view==='network')network();if(state.view==='flow')flow();if(state.view==='time')heat();$('inspector').innerHTML=details(state.node);chart('rate-chart');chart('queue-chart',true);if(space&&state.view==='space')space.draw();if(animate)animateInspector();document.body.dataset.index=state.index;document.body.dataset.node=state.node;}
function select(node,index=state.index,ev=null){if(!(node in names))return;const changed=node!==state.node||index!==state.index;state.node=node;state.index=Math.max(0,Math.min(11,index));if(changed)refresh();if(state.view==='flow'&&ev){$('float-tooltip').innerHTML=details(node);$('float-tooltip').hidden=false;positionTooltip(ev);if(changed)animateInspector();}}
function positionTooltip(ev){const tip=$('float-tooltip');let x=ev.clientX+18,y=ev.clientY+12;const r=tip.getBoundingClientRect();if(x+r.width>innerWidth-12)x=ev.clientX-r.width-18;if(y+r.height>innerHeight-12)y=innerHeight-r.height-12;tip.style.left=Math.max(10,x)+'px';tip.style.top=Math.max(10,y)+'px';}
['network-svg','flow-svg','heat-svg'].forEach(id=>{const root=$(id);function over(e){const el=e.target.closest('[data-node]');if(el)select(el.dataset.node,el.dataset.index===undefined?state.index:+el.dataset.index,e);}root.addEventListener('pointermove',over);root.addEventListener('focusin',over);root.addEventListener('pointerleave',()=>{$('float-tooltip').hidden=true;});});
['rate-chart','queue-chart','rate-change-chart','growth-change-chart'].forEach(id=>{$(id).addEventListener('pointermove',e=>{const rect=$(id).getBoundingClientRect(),p=$(id).createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform($(id).getScreenCTM().inverse());const i=Math.max(0,Math.min(11,Math.round((v.x-46)/62)));select(state.node,i);const s=samples[i];$('chart-tooltip').innerHTML=`<strong>${time(s.t)} · один момент во всей сети</strong><div><span>Приходит</span><b>${s.incoming}/мин</b></div><div><span>Обрабатывается</span><b>${num(s.output)}/мин</b></div><div><span>В очереди</span><b>${num(s.q)} · ${num(s.wait)} с</b></div>`;$('chart-tooltip').hidden=id!=='rate-chart';const host=$('rate-chart').getBoundingClientRect();$('chart-tooltip').style.left=Math.max(34,Math.min(e.clientX-host.left+12,host.width-195))+'px';});$(id).addEventListener('pointerleave',()=>{$('chart-tooltip').hidden=true;});$(id).setAttribute('tabindex','0');$(id).addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();select(state.node,state.index+(e.key==='ArrowRight'?1:-1));}});});
const viewMeta={network:['Куда движутся запросы','Наведи на узел — подсветятся его связи и расчёт справа.','Скорости — запросы в минуту. На схеме показано направление передачи.'],flow:['Сколько проходит по каждой ветке','Наведи на полосу — появится короткий расчёт с её значениями.','Толщина полос пропорциональна запросам в минуту.'],space:['Сеть, которую можно рассмотреть','Тащи мышью для вращения. Наведи на узел — увидишь расчёт справа.','Высота сервиса отражает нагрузку. Линии показывают связи, не расстояния.'],time:['Где и когда не хватает мощности','Веди по ячейкам: момент, графики и расчёт меняются вместе.','Загрузка свыше 100% означает, что вход больше производительности.']};
function switchView(view){state.view=view;document.body.dataset.view=view;document.querySelectorAll('.scene').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('.view-nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));const m=viewMeta[view];$('view-title').textContent=m[0];$('view-hint').textContent=m[1];$('scene-footnote').textContent=m[2];$('float-tooltip').hidden=true;$('chart-tooltip').hidden=true;if(view==='space'){if(!space)space=initSpace();else space.resize();}refresh();loadVotes();}
document.querySelectorAll('.view-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function initSpace(){try{
 const host=$('space-canvas'),labelHost=$('space-labels'),scene=new THREE.Scene();scene.background=new THREE.Color('#f9fcfe');scene.fog=new THREE.Fog('#f9fcfe',22,42);
 const camera=new THREE.PerspectiveCamera(40,1,.1,80),renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Объёмная сеть. Перетаскивайте для вращения, используйте колесо для масштаба.');renderer.domElement.setAttribute('tabindex','0');
 scene.add(new THREE.AmbientLight(0xffffff,.85));const light=new THREE.DirectionalLight(0xffffff,.9);light.position.set(4,10,8);scene.add(light);const cool=new THREE.DirectionalLight(0xb9e9ff,.55);cool.position.set(-6,3,-5);scene.add(cool);
 const grid=new THREE.GridHelper(24,32,0xd3e2ec,0xeaf1f6);scene.add(grid);const layout={ui:[-5,-2.4],api:[-5,2.4],router:[-2,0],search:[1.1,-3.3],analysis:[1.1,0],export:[1.1,3.3],success:[5,-1.7],queue:[5,3]};
 const meshes=[],groups={},labels={};let az=.25,elev=.78,distance=17,drag=null,velocity=0,frame=0;
 Object.entries(layout).forEach(([id,[x,z]])=>{const group=new THREE.Group();group.position.set(x,0,z);scene.add(group);groups[id]=group;const base=new THREE.Mesh(new THREE.CylinderGeometry(.64,.7,.13,40),new THREE.MeshStandardMaterial({color:0xeaf3f8,roughness:.35,metalness:.15}));base.position.y=.12;group.add(base);const ringMesh=new THREE.Mesh(new THREE.TorusGeometry(.63,.025,8,48),new THREE.MeshBasicMaterial({color:colors[id]}));ringMesh.rotation.x=Math.PI/2;ringMesh.position.y=.21;group.add(ringMesh);const h=['search','analysis','export'].includes(id)?1.65:id==='queue'?.9:1.1;const shell=new THREE.Mesh(new THREE.CylinderGeometry(.36,.43,h,32),new THREE.MeshStandardMaterial({color:colors[id],transparent:true,opacity:.27,metalness:.1,roughness:.25}));shell.position.y=h/2+.22;group.add(shell);const core=new THREE.Mesh(new THREE.CylinderGeometry(.22,.26,h*.8,24),new THREE.MeshStandardMaterial({color:colors[id],roughness:.3,emissive:colors[id],emissiveIntensity:.15}));core.position.y=h*.4+.22;group.add(core);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.4,.4,.08,32),new THREE.MeshStandardMaterial({color:0xffffff,metalness:.3,roughness:.25}));cap.position.y=h+.25;group.add(cap);group.userData.h=h;[base,shell,core,cap].forEach(m=>{m.userData.id=id;meshes.push(m);});const el=document.createElement('div');el.className='space-label';el.innerHTML=`<strong>${names[id]}</strong><span></span>`;el.addEventListener('pointermove',()=>select(id));labelHost.append(el);labels[id]=el;});
 edges.forEach(([a,b])=>{const aa=layout[a],bb=layout[b],mid=(aa[0]+bb[0])/2;const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(aa[0],.2,aa[1]),new THREE.Vector3(mid,.24,aa[1]),new THREE.Vector3(mid,.24,bb[1]),new THREE.Vector3(bb[0],.2,bb[1])]);const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,32,.027,5,false),new THREE.MeshBasicMaterial({color:a==='analysis'||b==='analysis'||b==='queue'?0xdbaf66:0x9bbfd5}));scene.add(tube);});
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
 function draw(){camera.position.set(Math.sin(az)*Math.cos(elev)*distance,Math.sin(elev)*distance,Math.cos(az)*Math.cos(elev)*distance);camera.lookAt(0,.4,0);camera.updateMatrixWorld();const s=samples[state.index];Object.entries(groups).forEach(([id,g])=>{g.children[1].material.color.set(id===state.node?'#efb148':colors[id]);if(['search','analysis','export'].includes(id)){const cap={search:60,analysis:30,export:36}[id],scale=.65+s[id]/cap*.5;g.children[2].scale.y=scale;g.children[2].position.y=.22+g.userData.h*scale/2;g.children[3].scale.y=scale;g.children[3].position.y=.22+g.userData.h*.8*scale/2;g.children[4].position.y=.25+g.userData.h*scale;}
 const projected=new THREE.Vector3(g.position.x,g.children[4].position.y+.2,g.position.z).project(camera);const el=labels[id];el.style.left=(projected.x*.5+.5)*host.clientWidth+'px';el.style.top=(-projected.y*.5+.5)*host.clientHeight+'px';el.classList.toggle('active',id===state.node);el.querySelector('span').textContent=num(rate(id,s))+(id==='queue'?' ждут':'/мин');});renderer.render(scene,camera);document.body.dataset.camera=az.toFixed(3)+','+elev.toFixed(3)+','+distance.toFixed(2);}
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();draw();}
 function inertia(){if(matchMedia('(prefers-reduced-motion:reduce)').matches){velocity=0;frame=0;return;}az+=velocity;velocity*=.86;draw();if(Math.abs(velocity)>.0005)frame=requestAnimationFrame(inertia);else frame=0;}
 host.addEventListener('pointerdown',e=>{if(frame)cancelAnimationFrame(frame);frame=0;velocity=0;drag={x:e.clientX,y:e.clientY};host.setPointerCapture(e.pointerId);});
 host.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;velocity=-dx*.005;az+=velocity;elev=Math.max(.2,Math.min(1.3,elev+dy*.004));drag={x:e.clientX,y:e.clientY};draw();}else{const rect=host.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(meshes);if(hits.length)select(hits[0].object.userData.id);}});
 const release=()=>{drag=null;if(!frame)frame=requestAnimationFrame(inertia);};host.addEventListener('pointerup',release);host.addEventListener('pointercancel',()=>{drag=null;velocity=0;});host.addEventListener('lostpointercapture',()=>{drag=null;});host.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(10,Math.min(27,distance+e.deltaY*.01));draw();},{passive:false});renderer.domElement.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')az-=.1;if(e.key==='ArrowRight')az+=.1;if(e.key==='ArrowUp')elev=Math.min(1.3,elev+.1);if(e.key==='ArrowDown')elev=Math.max(.2,elev-.1);if(e.key==='+')distance=Math.max(10,distance-1);if(e.key==='-')distance=Math.min(27,distance+1);draw();}});addEventListener('resize',resize);resize();document.body.dataset.webgl='ready';return {draw,resize};
 }catch(error){$('space-fallback').hidden=false;document.body.dataset.webgl='unavailable';return null;}}
function loadVotes(){const v=votes[state.view]||{};$('comment').value=v.comment||'';document.querySelectorAll('[data-vote]').forEach(b=>b.setAttribute('aria-pressed',String(v.vote===b.dataset.vote)));}
document.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{votes[state.view]={...votes[state.view],vote:b.dataset.vote};save();loadVotes();});$('comment').oninput=()=>{votes[state.view]={...votes[state.view],comment:$('comment').value};save();};
const techniques=[['linked','Связанные графики'],['panel','Расчёт в плашке'],['floating','Подсказка у курсора'],['motion','Анимация подстановки'],['hud','Тонкие рамки и метки'],['ribbons','Широкие потоки'],['orbit','Вращение 3D'],['heat','Карта нагрузки']];
techniques.forEach(([id,label])=>{const card=document.createElement('div');card.className='technique';card.innerHTML=`<span>${label}</span><div><button aria-label="${label}: оставить" data-choice="yes">+</button> <button aria-label="${label}: убрать" data-choice="no">−</button></div>`;card.querySelectorAll('button').forEach(b=>{b.setAttribute('aria-pressed',String(votes.techniques?.[id]===b.dataset.choice));b.onclick=()=>{votes.techniques={...votes.techniques,[id]:b.dataset.choice};card.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));save();};});$('techniques').append(card);});
$('export').onclick=()=>{const payload={version:2,subject:'Учебная сеть потоков',preferences:votes,reference:'https://photo-158-220-127-161.sslip.io/board/#stats'};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='design-preferences-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

window.flowLab={samples,state,select,switchView};refresh();loadVotes();
})();
