"""AgentBackend protocol — abstract interface for Claude/Codex/etc."""

from typing import AsyncIterator, Optional, Protocol, runtime_checkable

from app.events import AgentEvent


@runtime_checkable
class AgentBackend(Protocol):
    async def connect(self) -> None: ...
    async def send(self, message: str) -> None: ...
    def events(self) -> AsyncIterator[AgentEvent]: ...
    async def interrupt(self) -> None: ...
    async def disconnect(self) -> None: ...

    @property
    def session_id(self) -> Optional[str]: ...
